### ISSUE TITLE
Server Sign Not Working

### ISSUE THREAD

**Issue by lyalldaniel2009** [bumbummen99/SkyCraft#9] opened 2021-04-13 06:05 UTC
The server sign isn't working on my website. It always says offline even though it's on and all query port settings are set correctly.

**Comment by bumbummen99** [comment] 2021-04-17 16:40
@techyboy27 Can you please try the following configuration for the server sign:
Enable all options
Address: test.nitrado.net
Port: 25565

That is the Nitrado test server which should be reachable. I have just re-installed everything locally and it does work fine for me. If the server also does work for you it is probably being caused by the configuration of your minecraft server, else it is being caused by the web-server itself.

**Comment by lyalldaniel2009** [comment] 2021-04-17 16:46
> @techyboy27 Can you please try the following configuration for the server sign:
> 
> Enable all options
> 
> Address: test.nitrado.net
> 
> Port: 25565
> 
> 
> 
> That is the Nitrado test server which should be reachable. I have just re-installed everything locally and it does work fine for me. If the server also does work for you it is probably being caused by the configuration of your minecraft server, else it is being caused by the web-server itself.

It didn't work for me on your test server. I'll get in touch with InfinityFree and see if we can solve this.

**Comment by bumbummen99** [comment] 2021-04-17 17:30
What PHP version is your host configured to? [xPaw/PHP-Minecraft-Query](https://github.com/xPaw/PHP-Minecraft-Query) does require PHP >= 7.0. Also please update to latest version 3.1.3 :+1:

**Comment by lyalldaniel2009** [comment] 2021-04-17 18:05
> What PHP version is your host configured to? [xPaw/PHP-Minecraft-Query](https://github.com/xPaw/PHP-Minecraft-Query) does require PHP >= 7.0. Also please update to latest version 3.1.3 :+1: 

I'll go have a look!

**Comment by lyalldaniel2009** [comment] 2021-04-17 18:33
> What PHP version is your host configured to? [xPaw/PHP-Minecraft-Query](https://github.com/xPaw/PHP-Minecraft-Query) does require PHP >= 7.0. Also please update to latest version 3.1.3 :+1: 

Hi. I've updated to 3.1.3 and updated my php version from 7.0 to 7.4. Still no difference.

**Comment by bumbummen99** [comment] 2021-04-17 18:56
Could you insert the following code in your index.php before any other code after the `<?php`:
```
phpinfo();
exit(0);
```
And post the output of the installed extensions?

**Comment by techyboy27** [comment] 2021-04-17 18:59
Done that. What am I looking for?

**Comment by lyalldaniel2009** [comment] 2021-04-17 19:01
Done that. I now get a massive page of info when I go to my website instead of my homepage.

**Comment by lyalldaniel2009** [comment] 2021-04-17 19:02
Where do I find the extensions? 

(Update worked this time.)

**Comment by techyboy27** [comment] 2021-04-17 19:02
> Could you insert the following code in your index.php before any other code after the `<?php`:
> 
> ```
> 
> phpinfo();
> 
> exit(0);
> 
> ```
> 
> And post the output of the installed extensions?

Give me 10 mins. Looks like the update failed. I'll try again.

**Comment by bumbummen99** [comment] 2021-04-17 19:14
> Done that. I now get a massive page of info when I go to my website instead of my homepage.

Yeah that is intended :D It will list all information about your PHP-Server/Installation including version, configs. But i did get it wrong, sorry my mistake. What you will need to use instead of `phpinfo();` is `print_r(get_loaded_extensions());` according to:
https://stackoverflow.com/questions/478844/how-do-i-see-the-extensions-loaded-by-php

**Comment by lyalldaniel2009** [comment] 2021-04-17 19:16
Got that. I have a list of html stuff like MySQL .etc it starts with array (0 =>

**Comment by bumbummen99** [comment] 2021-04-17 20:09
> Got that. I have a list of html stuff like MySQL .etc it starts with array (0 =>

can you upload the full output somewhere? It should be an array of the installed modules

**Comment by lyalldaniel2009** [comment] 2021-04-17 20:13
> > Got that. I have a list of html stuff like MySQL .etc it starts with array (0 =>
> 
> 
> 
> can you upload the full output somewhere? It should be an array of the installed modules

Yeah I'll stick it down below:

Array ( [0] => Core [1] => date [2] => libxml [3] => openssl [4] => pcre [5] => sqlite3 [6] => zlib [7] => bcmath [8] => calendar [9] => ctype [10] => curl [11] => dom [12] => hash [13] => fileinfo [14] => filter [15] => ftp [16] => gd [17] => gettext [18] => gmp [19] => SPL [20] => iconv [21] => intl [22] => json [23] => mbstring [24] => session [25] => standard [26] => mysqlnd [27] => mysqli [28] => PDO [29] => pdo_mysql [30] => pdo_sqlite [31] => Phar [32] => Reflection [33] => mysql [34] => SimpleXML [35] => soap [36] => exif [37] => tokenizer [38] => xml [39] => xmlreader [40] => xmlrpc [41] => xmlwriter [42] => xsl [43] => zip [44] => apache2handler [45] => ionCube Loader )

**Comment by bumbummen99** [comment] 2021-04-18 02:03
Super strange, basically anything important is there. You will maybe have to contact your host as you said and tell them that you are trying to use this script if they ask:

[xPaw/PHP-Minecraft-Query](https://github.com/xPaw/PHP-Minecraft-Query)

To be honest with you, it has been **years** since i quit minecraft hosting and closing my server. I still support this theme but i do not use it myself anymore. I recall that back then there were certain webspace providers that had issues with PHP-Minecraft-Query but i am not sure anymore.

**Comment by techyboy27** [comment] 2021-04-19 14:39
Hi, is there a way for me to add the php thingy required for the Minecraft server?

**Comment by lyalldaniel2009** [comment] 2021-04-19 14:40
Hi how do I install the xpaw query php thing?

**Comment by bumbummen99** [comment] 2021-04-19 15:13
> 
> 
> Hi how do I install the xpaw query php thing?

It is already installed if you do use the theme 👍 It is the library the theme does use to query the minecraft servers, the theme itself basically only offers UI around and to configure this library.

**Comment by lyalldaniel2009** [comment] 2021-04-20 01:21
Ok.

**Comment by bumbummen99** [comment] 2021-04-20 18:48
> 
> 
> Ok.

May i ask what exact plan you have at InfinityFree?

**Comment by lyalldaniel2009** [comment] 2021-04-20 18:50
The free plan, it only does freeplans. The parent host is ifastnet which has premium hosting. I'm on the free plan with infinity free though.

**Comment by lyalldaniel2009** [comment] 2021-04-26 20:40
Hi, are you any further on fixing this?

**Comment by bumbummen99** [comment] 2021-04-27 20:01
> 
> 
> Hi, are you any further on fixing this?

So i tried setting up a small WordPress test site on the host myself but i did not even manage to get WordPress installed 😅 
I tried it using their FTP & Installer, booth times i got a white screen of death. I contacted their support about that issue but i did not yet get any response

**Comment by lyalldaniel2009** [comment] 2021-04-27 20:07
> > 
> 
> > 
> 
> > Hi, are you any further on fixing this?
> 
> 
> 
> So i tried setting up a small WordPress test site on the host myself but i did not even manage to get WordPress installed 😅 
> 
> I tried it using their FTP & Installer, booth times i got a white screen of death. I contacted their support about that issue but i did not yet get any response

Ahh yes, but did you use http or https! If using https, you'll need really simple ssl

**Comment by bumbummen99** [comment] 2021-04-27 21:36
> 
> 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > Hi, are you any further on fixing this?
> > 
> > 
> > So i tried setting up a small WordPress test site on the host myself but i did not even manage to get WordPress installed 😅
> > I tried it using their FTP & Installer, booth times i got a white screen of death. I contacted their support about that issue but i did not yet get any response
> 
> Ahh yes, but did you use http or https! If using https, you'll need really simple ssl

It does seem that it was just the DNS that had to propagate. So after installing and activating the theme it does seem to work fine. You can check it over here:

[InfinityFree Preview](http://skycraft-test.infinityfreeapp.com/)

That is with the latest WordPress 5.7.1 & SkyCraft 3.1.3 and no other Plugins installed.

**Comment by lyalldaniel2009** [comment] 2021-04-28 05:57
Oh yeah, it does work. Can you check the php version so I can update mine?

Thanks

**Comment by bumbummen99** [comment] 2021-04-28 06:13
> Oh yeah, it does work. Can you check the php version so I can update mine?
> 
> Thanks 

It should be on PHP 7.4 according to the interface and phpinfo.

**Comment by lyalldaniel2009** [comment] 2021-04-28 07:07
> > Oh yeah, it does work. Can you check the php version so I can update mine?
> > 
> > Thanks 
> 
> It should be on PHP 7.4 according to the interface and phpinfo.

So I made a new installation and used your test server and it worked! But none of my servers are working on it, they're on and working with another plugin on my main site as well. Ping and Query is on. It's a bungee network, so is bungee not supported?

**Comment by bumbummen99** [comment] 2021-05-01 12:18
> > > Oh yeah, it does work. Can you check the php version so I can update mine?
> > > Thanks
> > 
> > 
> > It should be on PHP 7.4 according to the interface and phpinfo.
> 
> So I made a new installation and used your test server and it worked! But none of my servers are working on it, they're on and working with another plugin on my main site as well. Ping and Query is on. It's a bungee network, so is bungee not supported?

It should also support Bungecoord afaik but i did not test that. It [does use MinecraftPing](https://github.com/xPaw/PHP-Minecraft-Query#ping) so you will have to make sure you are using **Minecraft 1.7+** or a server software that does support the protocol.

**Comment by lyalldaniel2009** [comment] 2021-05-01 12:42
> > > > Oh yeah, it does work. Can you check the php version so I can update mine?
> 
> > > > Thanks
> 
> > > 
> 
> > > 
> 
> > > It should be on PHP 7.4 according to the interface and phpinfo.
> 
> > 
> 
> > So I made a new installation and used your test server and it worked! But none of my servers are working on it, they're on and working with another plugin on my main site as well. Ping and Query is on. It's a bungee network, so is bungee not supported?
> 
> 
> 
> It should also support Bungecoord afaik but i did not test that. It [does use MinecraftPing](https://github.com/xPaw/PHP-Minecraft-Query#ping) so you will have to make sure you are using **Minecraft 1.7+** or a server software that does support the protocol.

So, it works with your test server when I install the theme. But I change it to my server and it says offline, when I'm connected to it and it's online. Then I change it back to your server and it says it's offline when it was on 30secs before.

**Comment by bumbummen99** [comment] 2021-05-01 13:07
> So, it works with your test server when I install the theme. But I change it to my server and it says offline, when I'm connected to it and it's online. Then I change it back to your server and it says it's offline when it was on 30secs before.

That is propanly due to the server query being scheduled by WP-Cron to be run every minute, that does mean it is not being run on every request but only after a minute. The result is then cached into a unique key generated from the configured ip&port combination. Due to it being changed, the cache key will change but there is no cached result yet causing the server to be offline temporarily - but it should come online again after a minute. If not then that is a bug :)

If you mind, could you share the ip port for your server?

**Comment by lyalldaniel2009** [comment] 2021-05-01 13:11
> > So, it works with your test server when I install the theme. But I change it to my server and it says offline, when I'm connected to it and it's online. Then I change it back to your server and it says it's offline when it was on 30secs before.
> 
> 
> 
> That is propanly due to the server query being scheduled by WP-Cron to be run every minute, that does mean it is not being run on every request but only after a minute. The result is then cached into a unique key generated from the configured ip&port combination. Due to it being changed, the cache key will change but there is no cached result yet causing the server to be offline temporarily - but it should come online again after a minute. If not then that is a bug :)
> 
> 
> 
> If you mind, could you share the ip port for your server?

Hi, it's a Java server running Paper/Bungee 1.16.5 and the port is 30061 as I'm hosting with FalixNodes.

**Comment by bumbummen99** [comment] 2021-05-02 08:22
> > > So, it works with your test server when I install the theme. But I change it to my server and it says offline, when I'm connected to it and it's online. Then I change it back to your server and it says it's offline when it was on 30secs before.
> > 
> > 
> > That is propanly due to the server query being scheduled by WP-Cron to be run every minute, that does mean it is not being run on every request but only after a minute. The result is then cached into a unique key generated from the configured ip&port combination. Due to it being changed, the cache key will change but there is no cached result yet causing the server to be offline temporarily - but it should come online again after a minute. If not then that is a bug :)
> > If you mind, could you share the ip port for your server?
> 
> Hi, it's a Java server running Paper/Bungee 1.16.5 and the port is 30061 as I'm hosting with FalixNodes.

If you can give me the full adress i could debug it. Otherwise you could try to configure other servers that have a similar setup to rule out that it is the firewall setup.

**Comment by lyalldaniel2009** [comment] 2021-05-02 11:53
> > > > So, it works with your test server when I install the theme. But I change it to my server and it says offline, when I'm connected to it and it's online. Then I change it back to your server and it says it's offline when it was on 30secs before.
> 
> > > 
> 
> > > 
> 
> > > That is propanly due to the server query being scheduled by WP-Cron to be run every minute, that does mean it is not being run on every request but only after a minute. The result is then cached into a unique key generated from the configured ip&port combination. Due to it being changed, the cache key will change but there is no cached result yet causing the server to be offline temporarily - but it should come online again after a minute. If not then that is a bug :)
> 
> > > If you mind, could you share the ip port for your server?
> 
> > 
> 
> > Hi, it's a Java server running Paper/Bungee 1.16.5 and the port is 30061 as I'm hosting with FalixNodes.
> 
> 
> 
> If you can give me the full adress i could debug it. Otherwise you could try to configure other servers that have a similar setup to rule out that it is the firewall setup.

Hi, my server IP is play.destructorcraft.cf/5.9.11.248.

**Comment by lyalldaniel2009** [comment] 2021-05-02 13:05
I'll explain further. 

The SRV Record IP is play.destructorcraft.cf and the Numeric IP is 5.9.11.248

**Comment by lyalldaniel2009** [comment] 2021-05-07 15:16
Hi, 
Put my server info above. 
Are we any further forward with this? 
Releasing my website as soon as this is fixed/with temporary theme.

**Comment by bumbummen99** [comment] 2021-05-07 16:19
> Hi,
> Put my server info above.
> Are we any further forward with this?
> Releasing my website as soon as this is fixed/with temporary theme.

Sorry i have been  abit busy. I have tested your server manually and it seems to connect but not work, this is the response i get from MinecraftPing:
```
Array
(
    [version] => Array
        (
            [name] => BungeeCord 1.8.x-1.16.x
            [protocol] => 754
        )

    [players] => Array
        (
            [max] => 25000
            [online] => 0
        )

    [description] => Array
        (
            [extra] => Array
                (
                    [0] => Array
                        (
                            [color] => red
                            [text] => [Bungee] Can't connect to server.
                        )

                )

            [text] => 
        )

    [favicon] => data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAASX0lEQVR4XuVbZ3QVR5qdP3N2MCZIQvkFSSjnnHPOOeeIcs4RZYEiIkkyyUgGJYQxFhgwmJwxaUgmCAljY9YzZ9a7Z3f27J+7VfV4IOsRBBa2DqNz7unu6qru/m7dL1S33p9slhXgQ4fRkkSof+T/UvxpZucPDWZiadBcGCRi+L8EARbiWdD6OFTE6H8JAqwkcqG7KELE4Jn4IAmwXpYP/cUxIsa+DB8kAYKgFyBi7MvwwRFgKrYCGgsDRQx9Ff5QAmyXFTLMbH9XmItnQGthsIiRr8MfREAhC1IG4uEwFI+ANdmnbaL9Zg9LiRzofBwmYuCb8AcQUAhziVToyLrDy7IQbia5ZN+DtKWxc6L93wxriTzoLYoSMW42+J0JKISZ+AoYKnqgMG4napLOwc0gHwGWtdDlUhJSWR/Rca9DPgyXxIsYNlv8TgTks631sjzoynugNHkY3QVTSHMeg5yEAkyUAhFs3QRdOQ/WZ/qYN8FkaQo0ZhnxX4b3TEA+7CRL4C7XAH9+F2zlMxBoX4P2nIcocD0OX6UWSC6RgbSYPLw0q+Cqnwt7Tjbr6yZXT8YWs2uIXlcAM7H015a5s8F7IiAfDlJl8Oauhr9iBxx5udCX84KynAFyw/eiMvhb+CxvgJtpDIz1LCG2RAwa0rYI0lsNFXkDGHJ84MjNg79CB7w4q2AvVcquOf0elqTM1X5DmTsbzDEBghn35lDD22DFSYA21wG2BrGIcGuDrWEMapOuIsZsC+wMAjD6yUUM95yHuY4LNCTtEaq1Fm6W0agr7kGwZyIMljvCSj4RfgpthIiWZ4oQlrmRIsa8C+aUAFfZWgQoroEdNw1aXDu4mmciP2IfVmU8QG7YXvjbV6Eh6Ras1SPg5uyJrPgaZMRWwdneDYYKLghX74WHcRaGes7i/Ph/YMf6k4gPzSNEOMCOk44AhS44y1STMjdWxJB3xRwRkE98tg6+is0kyLmSGY9GXvg4M7w1a4ohxLkJKf6fojTsBNR4BnB2coKMlDQkJZbBzs4aOkpmCFPpgZNmJmryN+Dywf/Btwf+Gxf2/YL+tccQ6B4PA647fBSbSCZJhdpHfiLGvAvmiIAC+PE7oC/viSCnOjSnfYe2rEdoTL2NyvgzKI87BTujWMR5bUC6yxiJBYbwt6uGt00J9NWcsXjRR5ATV0SY6kY4qWUj1DsV4/23sH/gDk5/8TOuHPwn2xamNcOI4wtn2ar5SYAexx05YXvYzCf6bIKLRQIxPALmukHgy6kyY1c4DMFA0QtFUYdQHHUYCvIaWLx4AVSlzRBuvBbqfDMo8zXgaB4KF8sohHilYm39Llzc/5/Y0nkQRjwvuMhVz08C9DmeyAgaIgGvFVF+uWjOP4TGtGuk4LmEZL9t0Fa2IcEvHt5mpQhyqEVpzFFwZZWxdMlieJmWwkInBNoqtljh34+axG9Rm3wVWcG74Wgaj/qiTdjY8gWMuD7zUQH58ON1kPTlCx+bUsQGFmO4+yHWFD4iaphgiqCoiD8FI00PuJimw1o7Gmba/pCV5MBCPRRu5jkw1fZFZcJZ0vc+67+ajb2PzOBdRBGRyEmqhQkvAE6ylfOPAF9eO4zk/aGnYYPyzC6MbLiF7qIpZkh9wg2ke46iLPAM0txGoKVkjVDrVtgrpsNRMQuRdt3QVXZEhvsYSgJOIsZ1A6rizgtIyJxgCvKwzIGepjFMuSFwlCmbXwTQNzA+3DYYyQWCIysPX5cIbFx5gT08NaIm/CqC9EltsHwVErV2wU29GBpKFoiz2IYU6xEYqLnBQ72cnfNUrIGCrCbiPfvQQmafXqMqgawZLLIgK8WBqXwY7KSLobZgnhHgRYofC0408eePEeaTiuasC0z+jcl3UB5+BnFOm+CkmId49UHEan4GU0VSwiqYQ1/VFRbLIxCnuYOcG4YLvwhOuukoCzuFhuSbzA0aVtyAvVEcJMTEYcmJg7Vk3vwjwEO+CTbcFJLbpZAd2462bOrHE6gIvQAbpQTIivOhImWCKLWtz0joh7qMJbjLVBGpsRlxpC1efQgeilVQljKCHs8NBcEHiQIeMkS4tkFs6RLY8dJhIZE5/1zATbae1Px5UOIpo7fpGLbUP0ZHHnGB9AfI9h6HsowBW/QELG9nhsapDUJL2hH8ZVqMlDj1nUwB7ooVECdrAx/LUrSkC4IhBc0YPFlVOPHyYSKWMr8IoEGQlqjufBKdlbSRFFGIvlUHMNz1hFSBD1EVeQlWKjFk0bMEJgq+CNKtR4QhCZrKrlCS0kG4Sh9iVXcyUmw4yTAmMaEx7eLzDJJOUquLWTqJDRpw41fAYEnsfCOggKz+ylkpLC0mh9jgbPS3TqAzbxJF/sdgrOBPZnUpJMTF4WQRiWCXIpQnj6Ih4wRyI7YjN2A7Mlw2I8igBjwpFST7NKK/5TFxI0rABKkHrrBKUo64kSe/HjqLwkUMeVfMGQF0peav2A4VOX10VY+ju/B7VAQT/1dIgqwYH1KEGEkJSbgYZ8DPuhIlUUeJOh4RTDJX2Vh1FxtrSeYo3YPexqMY7bmO7asEBDSn3UWs13ro8Bzhwa37ze8ApmPOCKCvsnx4q6DNt0RnxSG050wi02YfUUUTrLmJ0JVxg6a0Hcw4YTDnRSLSsIfVBU1pd5iRLSRWtJJg15k3hXUlj9BTNYUN5ZPMBWg6DHdthT7fgxRBZSJG/BbMIQH58OQ0QY/rhIaCEQx2PEWp11H4K62GAz8bwSprEas+gGi1TxGisg5eiivhubwaK+xHUB9/SxDsntUNlAwh2Ioyc5IRoC3rRFJg7pz5P8WcEuAqWwcrXhwqc9bh8OBP6Mi5jQSTnYhRG2BpjkZ6QbQfZG1eSrUs70do9yDX5SBqo6+jJe3+cyKEaEq7jSDHOpjJRZEMkDxfCaCBsAyevDoEOCWjrWoHPqmdILN7G9m2B5GgNfycgBcYRLhqL5z5+bDjpiNaaxvSLPegPPACmlPvsfxPi6BYz/WwIWsHV27lnLwGm445JYDCj99J6vVgqKtoIiWsCSuTz6Mh5RZKfc8gQXOY5foXGGJqCFftg7l8JNSkLGEmH450tzHUJl1BRdxp+NtVgS+vSmJHOPH/CvLQczf7FHNMgKAeoG9taOTXUraEi3kavG2KkeY1BGeFPDjyc+DEzyNxIQtW3HjoyXqSYkgTEkvF2XsBWu3pqjjAXNcPwR4ZcLTyJtWiCrwU6kn+j5tT+VPMMQEC+HBb4cDLhqGqBxJ8+uBslopC/2/gvbyOLWaWSxpCRpzLCqMlZO2wbKkk5MWVoCFtAweFDMQ69sHS0B1dtYOwN/VmFSZdAM18+LnAeyHAVrKIuYIDLwuqHGPoqTsiyWkAMer9TPI0EwQrr4GqlDk4EsrwUWpAmGoPyRKfETcZQqBpE3gcBbJEtiDXyGFvgDTf4ovv2+C9EEBBSaBLZE+FGmjK2kKDY8kk761UR1JiN/N7LWkHthagaTFUZT3JCithIh9MqkE1qEtbw4NfAwfp0jktfGbivREgBP3CE6DYxdRAP36oSplBX9abkJEAc04kM9icEwUdGWcoSeqRPtZE8jnw4jXDVDxV5IHnGu+dAAoL8Uy2hvfkNcKVXwpj+SCy5DUm8lcBl4Auk03kQ8hCp5z1sVyWzb7zz3XAexneOwHsP7UWhkBtgS+TMi1knGQqyAw3MYl78FeyfUfSZrw0mfX5PQwX4pUEWEvkw0pcABsJwbE13ZJjW0l6LGwT4kWblVgeG2MpTv9pIZy9vVH7i8Aouq/6F19ofBQE3UVRgu/6C2iAE7SzvqyP4Jg96AJ/dqyxULBVW/DiOtOvK3xLJNwX9nvd2yMRAqjBsVat+HzraYz0HkeyUyca0ndg/+AFdJXuRl5gDw6NfouBNYeR4bUOY5tO4suBc2jOGiSruS/xZf9ZrModRqJDBzY07EZmaDOaishS16oQw1sOYmDjOMLtS7G5czdGP/0adXl9SParw97BY1hTtwNeBlnY2r0HOz/5CimknT6knngIWkq2YHzkBAriOpDovRIjWw+hr20XnDVT4a6bwfrnRbfBTiUJn67bi+3r96IkqQvDmw+yvtEuFVD9t2eEvo4Ay6V5KA77BE8f/wO3rzzCvh3nmfGTd58SAsZwaNe3uH5uAo/u/zvWVu7BucO38fOTX5jRtP3a2Qek709kRTiMm1ceoHf1KE4fucoe6M71h5i4+xjdxNDdA0fwyz/+C63l2/DNvgu4eOomJu/9iMbCTZi8/yM7vnDyBvQlwuChn8nazh//K2vf2DJMrvMD7t2aQufKAWRHrAL9oyRSop/++HfsIuTmxbThuxuTuHtzCuEOpS8U9SYCSiI24Q4xfnjjMXzzxVUcHLnESPDXqsVXQxdxcv9f0Vs/jijzVWgvGsWl43fhrVpNjJ/AtrZDuHPtEbpWfoYbl+8/J2Bk60F8sfMYPv/sG5SldLNZvH1tAvZkxk5+fRk9q0dw7eJddFT34+bVB1jXOMiOjaUj4WuSy4xtq9yOA7tPo7d1lJFGFbGpY4wp7Mnjv+HkocuIci4nRP6AZN86aC4KxCBRBsXLZv/1BFz9nrkAJYAa/b///D98vu008oN68fDOT4wQVxK1O0vGcOnEXfioVeP6+Ye4eWmKGDaJ2tzeXymAypAa76qTTur9aKzwryf9HsJBLZkR0Ne6C9cv3UV71XZMPXiCq+e/w7GvLkJnaTAj4MF3jxHtWskk317Vj0cTTwgpj5hiqDudOnwFV87dIW5Tj7///AubdaqcnX37MbTpwPNYMROvJoAoYGiaAr4eu4xwk2aURm5mvv79g59RENyLtsLRZwTUMBf47sZDXDhxg/hjK5vJjS0jv1IAfaCCuHYyQ7W/IkCoACEB1IChzQegQmbOz5Qq4BGLA7v7j2BD8zAeTz5lbkHlT6X/9d5zrE9xYhceEgXQ++uKhWCQGP/WBBSHb8LUvac49dUNHCaGHxi+yGROA+CRz6/g+Ph1TNx6grLoLc8J8FarwtWz90gA+oIZUpO1EQ/ufI/x4RPMQGr4maPXyCzfY4EvyYcQQGKCvWoyjh24hH2jJ5nMV5OYQF1jOwlkJ4iktZcEw8c4h/n8nh1HcfnsbRb86DWPjJ/H+qYhnD16Hfdvf4+/Pf0HVpVtw90bUywwKv/Zh5FIMWsCaApLc+9ms3n1zAPUrRjAJ037ce/GDxhcfxSr84aZe5z9+hbCjJpQFf8pdm85CTteBpN5VcZ6JnUa2ffvOolbRAX1+X1IDWzAlfN3WGCjgSrMvgR7h44zd1iZ3cPI+Ir4d4xbJSONxomx/sMsBpjIRpH9I4wYGhsqUtexSN9V+xlRzijGth9GWmAjvhw+jsaCTWy8k8YKph4aUyhelQpFCKCwlymCm2IFXHll7NiJU8re1ztzS2EnVQhP5Sp2juZ9R9liWMtmsMWKwbIw5rMGkuHQIgFIXyKUGaj5sWAhQw2hBtF9rcVBMCT9NBYGsPPm3Bjok/EaHwewdh0y8+w8OaYPT+VszomBNhlH70GzA22j9xTej+7riYeyccJ70mOKmYa/lgAKYWHz62NBYUSLIbYlbaZLU4m8BA9JGWcFCtmyguVZMSMsWl5AUJw870/bpu1PvwYtguh1XnZ9asDMdmEBNNPQV+GVBIiAGEsVEGvdSqJ/GZN/gF41WdQkwk03nc2Cv3k+zMgseZJixk45CaZyUbBSiIeRdATpkwELXiwciM976GUyNXgbZbNx7noZcFRLYeqgY+kM0nP0kxqdZRon6NbLMBvGMpEsJlgrJjASDKXCSbtgDL0uVdyr5P4yzJoAViES42kxlOKyBt0VuxHtXI1Qu2KW8qhxRfGdzPdoYMoIaWa5Pp8UI6F2JWTbzkiJcCxjiPOoRnnqWoTYFKOzZoD1S/CsYWNoqqTZI4lkClrBtZRuhTcxvjanl5FKCxxKCnWjGJIaU0hKpemRpkTb5YnvhwAq/0DdOlb+eqpUIt61nhUx1OBgmyLm7/YqyWxGfExy2Oy5EUNowKOzHUZIoFuqCNqHzniIbTHzazrbtIR1VE95riKa++k1XLXT2MzTfQoaE+hYqgg625SIQIsCtk/H05gy08jXYdYECEgQKMFwccJzvxT47Qt/pFuhjwvPvdgKFyfCxcyv+zC8pG36/vT7CPenP8tMA9+EtyKAwlQs9a1+kDDf8VYEmItnvvUPEuY7Zk3Au/4gYb5jVgT8lh8kzHfMgoDf9oOE+Y43EvBbf5Aw3/FaAubiBwnzHa8kgL7NnesvsfMRLyXgQw56M/H/IA5E8azud5wAAAAASUVORK5CYII=
    [modinfo] => Array
        (
            [type] => FML
            [modList] => Array
                (
                )

        )

)
```

Bungee gives the Ping_cannot_connect error from here:
https://github.com/SpigotMC/BungeeCord/blob/72b3bdf6765bb703d4481b65e12d056d43abc9e0/proxy/src/main/resources/messages.properties#L25

**Comment by lyalldaniel2009** [comment] 2021-05-07 16:21
Hi. This should be correct. I'm currently setting up my servers. The bungee is always online though.

**Comment by bumbummen99** [comment] 2021-05-07 16:50
> Hi. This should be correct. I'm currently setting up my servers. The bungee is always online though.

Just let me know when they are in a debuggable state :)

**Comment by lyalldaniel2009** [comment] 2021-05-07 16:58
They are already. They aren’t joinable though.

**Comment by lyalldaniel2009** [comment] 2021-05-07 19:51
Hi,
Just thought I'd let you know that I've reset and wiped all of my servers as I'll be working on them for the next few months. My issue isn't just with my server, it's with big servers like Hypixel, CubeCraft and more.

**Comment by bumbummen99** [comment] 2021-05-18 19:50
> 
> 
> Hi,
> Just thought I'd let you know that I've reset and wiped all of my servers as I'll be working on them for the next few months. My issue isn't just with my server, it's with big servers like Hypixel, CubeCraft and more.

Hey, sorry for the late reply. I fear i do not fully understand what you mean by that. Is it related to the specific Bungee build you are using for the server-network or the Hoster?

**Comment by lyalldaniel2009** [comment] 2021-05-18 19:54
Hi, I have wiped all my servers, linked to the bungeecord and including the
bungeecord. My issue isn’t just with my servers, if I go add a server like
Hypixel to the server sign, it doesn’t work either.

**Comment by bumbummen99** [comment] 2021-05-18 21:35
> Hi, I have wiped all my servers, linked to the bungeecord and including the bungeecord. My issue isn’t just with my servers, if I go add a server like Hypixel to the server sign, it doesn’t work either.


Check out the latest update, it does seem to work with `mc.hypixel.com` now. It seems that the query library has an issue getting the description as an well formed array.

You can check it working at https://skycraft.skyraptor.eu/

**Closed as completed** 2021-07-18 20:22 UTC
Labels: bug, Query
